#!/bin/bash

cat > /etc/bind/named.conf.domains/$1.conf <<EOF
zone "$1" {
  type master;
  file "/etc/bind/named.conf.domain/db.$1";
};
EOF

cat > /etc/bind/named.conf.domain/db.$1 <<EOF
$TTL	604800
@	IN	SOA	$1. root.$1. (
			      2		; Serial
			 604800		; Refresh
			  86400		; Retry
			2419200		; Expire
			 604800 )	; Negative Cache TTL
;
@	          IN  A    $2
EOF
